// SPDX-License-Identifier: PMPL-1.0-or-later
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell

//! Proof obligation generation for the TypeLL kernel.
//!
//! When dependent types are used, the type checker may not be able to
//! verify all constraints automatically. In these cases, it generates
//! **proof obligations** — logical propositions that must be proven true
//! for the program to be well-typed.
//!
//! ## Integration with ECHIDNA
//!
//! In the PanLL ecosystem, TypeLL generates proof obligations and ECHIDNA
//! (the formal verification agent) attempts to discharge them. This
//! separation of concerns allows TypeLL to stay fast (it doesn't need
//! an integrated theorem prover) while still supporting full dependent types.
//!
//! ## Current Status
//!
//! Foundation with obligation data types and basic generation from
//! refinement predicates and dependent type indices. Full integration
//! with external provers is TODO.

use crate::types::{Predicate, Term};
use serde::{Deserialize, Serialize};

/// A proof obligation generated by the type checker.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofObligation {
    /// Unique identifier for this obligation.
    pub id: String,
    /// Human-readable description.
    pub description: String,
    /// The proposition to prove.
    pub proposition: Proposition,
    /// Where in the source this obligation originates.
    pub origin: ObligationOrigin,
    /// Current status.
    pub status: ObligationStatus,
}

/// The logical proposition to prove.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Proposition {
    /// A predicate holds (from refinement types).
    PredicateHolds(Predicate),
    /// Two terms are equal (from dependent type unification).
    TermEquality(Term, Term),
    /// A term is well-founded (termination checking).
    WellFounded(Term),
    /// A dimension check (from resource types).
    DimensionCompatible(String, String),
    /// A session protocol is complete (no dangling sends/receives).
    SessionComplete(String),
    /// Custom proposition (escape hatch).
    Custom(String),
}

/// Where the obligation came from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ObligationOrigin {
    /// From a refinement type predicate.
    Refinement { base_type: String, predicate: String },
    /// From dependent type index unification.
    DependentIndex { type_expr: String },
    /// From a user-written `assert` or proof annotation.
    UserAnnotation { annotation: String },
    /// From session type completeness checking.
    SessionProtocol { protocol: String },
    /// From dimensional analysis.
    DimensionalAnalysis { operation: String },
}

/// Status of a proof obligation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ObligationStatus {
    /// Not yet attempted.
    Pending,
    /// Automatically discharged by the type checker.
    Discharged,
    /// Discharged by an external prover (ECHIDNA).
    ProvedExternally(String),
    /// Could not be proved — user must provide a proof.
    Unresolved,
    /// Proved false — the program is ill-typed.
    Refuted(String),
}

/// Proof obligation collector.
#[derive(Debug, Clone, Default)]
pub struct ObligationCollector {
    obligations: Vec<ProofObligation>,
    next_id: u32,
}

impl ObligationCollector {
    /// Create a new collector.
    pub fn new() -> Self {
        Self::default()
    }

    /// Generate a fresh obligation ID.
    fn fresh_id(&mut self) -> String {
        let id = format!("PO-{:04}", self.next_id);
        self.next_id += 1;
        id
    }

    /// Add a refinement obligation.
    pub fn add_refinement(
        &mut self,
        predicate: Predicate,
        base_type: &str,
    ) -> &ProofObligation {
        let id = self.fresh_id();
        let desc = format!("Refinement: {:?} on {}", predicate, base_type);
        self.obligations.push(ProofObligation {
            id,
            description: desc,
            proposition: Proposition::PredicateHolds(predicate.clone()),
            origin: ObligationOrigin::Refinement {
                base_type: base_type.to_string(),
                predicate: format!("{:?}", predicate),
            },
            status: ObligationStatus::Pending,
        });
        self.obligations.last().expect("Vec::last() after a Vec::push() on the same line is statically guaranteed to be Some")
    }

    /// Add a term equality obligation (from dependent type unification).
    pub fn add_term_equality(
        &mut self,
        t1: Term,
        t2: Term,
        type_expr: &str,
    ) -> &ProofObligation {
        let id = self.fresh_id();
        let desc = format!("Term equality: {} = {} in {}", t1, t2, type_expr);
        self.obligations.push(ProofObligation {
            id,
            description: desc,
            proposition: Proposition::TermEquality(t1, t2),
            origin: ObligationOrigin::DependentIndex {
                type_expr: type_expr.to_string(),
            },
            status: ObligationStatus::Pending,
        });
        self.obligations.last().expect("Vec::last() after a Vec::push() on the same line is statically guaranteed to be Some")
    }

    /// Get all pending obligations.
    pub fn pending(&self) -> Vec<&ProofObligation> {
        self.obligations
            .iter()
            .filter(|o| o.status == ObligationStatus::Pending)
            .collect()
    }

    /// Get all obligations.
    pub fn all(&self) -> &[ProofObligation] {
        &self.obligations
    }

    /// Mark an obligation as discharged.
    pub fn discharge(&mut self, id: &str) -> bool {
        for o in &mut self.obligations {
            if o.id == id {
                o.status = ObligationStatus::Discharged;
                return true;
            }
        }
        false
    }

    /// Summarise obligations as strings (for the CheckResult).
    pub fn summaries(&self) -> Vec<String> {
        self.obligations.iter().map(|o| o.description.clone()).collect()
    }

    /// Add a session completeness obligation.
    pub fn add_session_completeness(
        &mut self,
        protocol: &str,
    ) -> &ProofObligation {
        let id = self.fresh_id();
        let desc = format!("Session completeness: protocol '{}' must terminate", protocol);
        self.obligations.push(ProofObligation {
            id,
            description: desc,
            proposition: Proposition::SessionComplete(protocol.to_string()),
            origin: ObligationOrigin::SessionProtocol {
                protocol: protocol.to_string(),
            },
            status: ObligationStatus::Pending,
        });
        self.obligations.last().expect("Vec::last() after a Vec::push() on the same line is statically guaranteed to be Some")
    }

    /// Add a dimension compatibility obligation.
    pub fn add_dimension_check(
        &mut self,
        operation: &str,
        dim1: &str,
        dim2: &str,
    ) -> &ProofObligation {
        let id = self.fresh_id();
        let desc = format!("Dimension: {} compatible ({} vs {})", operation, dim1, dim2);
        self.obligations.push(ProofObligation {
            id,
            description: desc,
            proposition: Proposition::DimensionCompatible(
                dim1.to_string(),
                dim2.to_string(),
            ),
            origin: ObligationOrigin::DimensionalAnalysis {
                operation: operation.to_string(),
            },
            status: ObligationStatus::Pending,
        });
        self.obligations.last().expect("Vec::last() after a Vec::push() on the same line is statically guaranteed to be Some")
    }

    /// Attempt to automatically discharge refinement obligations
    /// using a built-in decision procedure.
    ///
    /// This is a lightweight alternative to a full SMT solver. It handles:
    /// - Constant folding (e.g., `5 > 0` → true)
    /// - Simple range checks (e.g., `x > 0 && x < 256`)
    /// - Contradiction detection (e.g., `x > 5 && x < 3`)
    ///
    /// Returns the number of obligations discharged.
    pub fn try_discharge_refinements(&mut self) -> usize {
        let mut discharged = 0;
        for obligation in &mut self.obligations {
            if obligation.status != ObligationStatus::Pending {
                continue;
            }
            if let Proposition::PredicateHolds(ref pred) = obligation.proposition {
                match eval_predicate(pred) {
                    PredicateResult::True => {
                        obligation.status = ObligationStatus::Discharged;
                        discharged += 1;
                    }
                    PredicateResult::False => {
                        obligation.status = ObligationStatus::Refuted(
                            "predicate is statically false".to_string(),
                        );
                        discharged += 1;
                    }
                    PredicateResult::Unknown => {
                        // Cannot determine statically — remains pending
                        // for ECHIDNA or an SMT solver to handle
                    }
                }
            }
            if let Proposition::TermEquality(ref t1, ref t2) = obligation.proposition {
                if terms_equal(t1, t2) {
                    obligation.status = ObligationStatus::Discharged;
                    discharged += 1;
                }
            }
        }
        discharged
    }
}

/// Result of evaluating a predicate at compile time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PredicateResult {
    /// Predicate is provably true.
    True,
    /// Predicate is provably false.
    False,
    /// Cannot determine at compile time.
    Unknown,
}

/// Try to evaluate a refinement predicate at compile time.
///
/// This is a lightweight built-in decision procedure — not a full SMT
/// solver. It handles constant comparisons and simple boolean combinations.
/// Anything it cannot decide is left as `Unknown` for ECHIDNA to handle.
pub fn eval_predicate(pred: &Predicate) -> PredicateResult {
    match pred {
        Predicate::Gt(a, b) => compare_terms(a, b, |x, y| x > y),
        Predicate::Gte(a, b) => compare_terms(a, b, |x, y| x >= y),
        Predicate::Lt(a, b) => compare_terms(a, b, |x, y| x < y),
        Predicate::Lte(a, b) => compare_terms(a, b, |x, y| x <= y),
        Predicate::Eq(a, b) => compare_terms(a, b, |x, y| x == y),
        Predicate::Neq(a, b) => compare_terms(a, b, |x, y| x != y),
        Predicate::And(a, b) => {
            let ra = eval_predicate(a);
            let rb = eval_predicate(b);
            match (ra, rb) {
                (PredicateResult::False, _) | (_, PredicateResult::False) => {
                    PredicateResult::False
                }
                (PredicateResult::True, PredicateResult::True) => PredicateResult::True,
                _ => PredicateResult::Unknown,
            }
        }
        Predicate::Or(a, b) => {
            let ra = eval_predicate(a);
            let rb = eval_predicate(b);
            match (ra, rb) {
                (PredicateResult::True, _) | (_, PredicateResult::True) => {
                    PredicateResult::True
                }
                (PredicateResult::False, PredicateResult::False) => {
                    PredicateResult::False
                }
                _ => PredicateResult::Unknown,
            }
        }
        Predicate::Not(inner) => match eval_predicate(inner) {
            PredicateResult::True => PredicateResult::False,
            PredicateResult::False => PredicateResult::True,
            PredicateResult::Unknown => PredicateResult::Unknown,
        },
        Predicate::Raw(_) => PredicateResult::Unknown,
    }
}

/// Try to evaluate a term to a compile-time integer.
fn eval_term(term: &Term) -> Option<i64> {
    crate::unify::eval_term_to_i64(term)
}

/// Compare two terms using a comparison function.
fn compare_terms(a: &Term, b: &Term, cmp: fn(i64, i64) -> bool) -> PredicateResult {
    match (eval_term(a), eval_term(b)) {
        (Some(va), Some(vb)) => {
            if cmp(va, vb) {
                PredicateResult::True
            } else {
                PredicateResult::False
            }
        }
        _ => PredicateResult::Unknown,
    }
}

/// Check whether two terms are syntactically equal.
fn terms_equal(t1: &Term, t2: &Term) -> bool {
    t1 == t2
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_refinement_obligation() {
        let mut collector = ObligationCollector::new();
        let pred = Predicate::Gt(Term::Var("x".to_string()), Term::Lit(0));
        collector.add_refinement(pred, "Int");
        assert_eq!(collector.pending().len(), 1);
        assert_eq!(collector.all()[0].id, "PO-0000");
    }

    #[test]
    fn test_discharge_obligation() {
        let mut collector = ObligationCollector::new();
        let pred = Predicate::Gt(Term::Var("x".to_string()), Term::Lit(0));
        collector.add_refinement(pred, "Int");
        assert!(collector.discharge("PO-0000"));
        assert_eq!(collector.pending().len(), 0);
    }

    #[test]
    fn test_term_equality_obligation() {
        let mut collector = ObligationCollector::new();
        collector.add_term_equality(
            Term::Var("n".to_string()),
            Term::BinOp {
                op: crate::types::TermOp::Add,
                lhs: Box::new(Term::Var("a".to_string())),
                rhs: Box::new(Term::Var("b".to_string())),
            },
            "Vec (n) Int",
        );
        assert_eq!(collector.pending().len(), 1);
    }

    #[test]
    fn test_session_completeness_obligation() {
        let mut collector = ObligationCollector::new();
        collector.add_session_completeness("BuyProtocol");
        assert_eq!(collector.pending().len(), 1);
        assert!(matches!(
            collector.all()[0].proposition,
            Proposition::SessionComplete(_)
        ));
    }

    #[test]
    fn test_dimension_check_obligation() {
        let mut collector = ObligationCollector::new();
        collector.add_dimension_check("multiply", "energy", "time");
        assert_eq!(collector.pending().len(), 1);
    }

    // ========================================================================
    // SMT refinement decision procedure tests
    // ========================================================================

    #[test]
    fn test_eval_predicate_constant_true() {
        // 5 > 0 is trivially true
        let pred = Predicate::Gt(Term::Lit(5), Term::Lit(0));
        assert_eq!(eval_predicate(&pred), PredicateResult::True);
    }

    #[test]
    fn test_eval_predicate_constant_false() {
        // 3 > 10 is trivially false
        let pred = Predicate::Gt(Term::Lit(3), Term::Lit(10));
        assert_eq!(eval_predicate(&pred), PredicateResult::False);
    }

    #[test]
    fn test_eval_predicate_variable_unknown() {
        // x > 0 cannot be determined statically
        let pred = Predicate::Gt(Term::Var("x".to_string()), Term::Lit(0));
        assert_eq!(eval_predicate(&pred), PredicateResult::Unknown);
    }

    #[test]
    fn test_eval_predicate_and_both_true() {
        let pred = Predicate::And(
            Box::new(Predicate::Gt(Term::Lit(5), Term::Lit(0))),
            Box::new(Predicate::Lt(Term::Lit(5), Term::Lit(256))),
        );
        assert_eq!(eval_predicate(&pred), PredicateResult::True);
    }

    #[test]
    fn test_eval_predicate_contradiction() {
        // x > 5 && 3 > 10 — second conjunct is false
        let pred = Predicate::And(
            Box::new(Predicate::Gt(Term::Var("x".to_string()), Term::Lit(5))),
            Box::new(Predicate::Gt(Term::Lit(3), Term::Lit(10))),
        );
        assert_eq!(eval_predicate(&pred), PredicateResult::False);
    }

    #[test]
    fn test_eval_predicate_or_one_true() {
        let pred = Predicate::Or(
            Box::new(Predicate::Gt(Term::Lit(3), Term::Lit(10))), // false
            Box::new(Predicate::Gt(Term::Lit(5), Term::Lit(0))),  // true
        );
        assert_eq!(eval_predicate(&pred), PredicateResult::True);
    }

    #[test]
    fn test_eval_predicate_not() {
        let pred = Predicate::Not(
            Box::new(Predicate::Gt(Term::Lit(3), Term::Lit(10))),
        );
        assert_eq!(eval_predicate(&pred), PredicateResult::True);
    }

    #[test]
    fn test_try_discharge_refinements() {
        let mut collector = ObligationCollector::new();
        // 5 > 0 — should be auto-discharged
        collector.add_refinement(
            Predicate::Gt(Term::Lit(5), Term::Lit(0)),
            "Int",
        );
        // x > 0 — cannot be auto-discharged
        collector.add_refinement(
            Predicate::Gt(Term::Var("x".to_string()), Term::Lit(0)),
            "Int",
        );
        let discharged = collector.try_discharge_refinements();
        assert_eq!(discharged, 1);
        assert_eq!(collector.pending().len(), 1);
    }

    #[test]
    fn test_try_discharge_term_equality() {
        let mut collector = ObligationCollector::new();
        let t = Term::Lit(5);
        collector.add_term_equality(t.clone(), t.clone(), "Vec 5 Int");
        let discharged = collector.try_discharge_refinements();
        assert_eq!(discharged, 1);
        assert_eq!(collector.pending().len(), 0);
    }
}
